/* =========================================================
   Script Purpose: Gold Layer Magnitude Analysis
   =========================================================
   This script explores key business breakdowns using the Gold
   layer star schema (dimensions + fact) to understand customer,
   product, and sales performance.

   What it covers:
   1) Customer Distribution
      - Total customers by country
      - Total customers by gender
      Use case: understand customer base composition and major markets.

   2) Product Portfolio Overview
      - Total products by category
      - Average product cost by category
      Use case: review product mix and cost profile across categories.

   3) Revenue Analysis
      - Total revenue by product category
      - Total revenue by customer (top customers by spend)
      Use case: identify top-performing categories and high-value customers.

   4) Sales Volume by Geography
      - Total quantity sold by country
      Use case: compare demand levels across regions.
   ========================================================= */

-- Find Total Customers by Countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find Total Customers by Gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find Total Products by Category
SELECT 
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the Average Costs in each Category?
SELECT 
    category,
    AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- What is the Total Revenue generated for each Category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- What is the Total Revenue generated by each Customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distributions of Sold Items across Countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.country
ORDER BY total_sold_items DESC;
